//
//  FeedDetailViewController.swift
//  TheVargo
//
//  Created by Andre Souza on 09/07/2018.
//  Copyright (c) 2018 AndreSamples. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit
import AlamofireImage


final class FeedDetailViewController: UIViewController {
    
    @IBOutlet weak var feedItemBookmarkButton: UIButton!
    
    @IBOutlet weak var feedItemImageView: VImageView!
    @IBOutlet weak var feedItemPlayerImageView: UIButton!
    
    @IBOutlet weak var feedItemDateLabel: UILabel!
    
    @IBOutlet weak var feedItemTitleLabel: UILabel!
    @IBOutlet weak var feedItemDescriptionLabel: UILabel!
    
    @IBOutlet weak var feedItemAuthorsTitleLabel: UILabel!
    @IBOutlet weak var feedItemAuthorsLabel: UILabel!
    
    @IBOutlet weak var feedItemFontTitleLabel: UILabel!
    @IBOutlet weak var feedItemUrlButton: UIButton!
    
    @IBOutlet weak var feedRelatedVideosContainerHeight: NSLayoutConstraint!
    @IBOutlet weak var feedRelatedVideosContainerBottom: NSLayoutConstraint!
    @IBOutlet weak var feedRelatedVideosContainer: UIView!
    @IBOutlet weak var collectionView: UICollectionView!
    
    @IBOutlet weak var feedRelatedVideosLoadingLabel: UILabel!
    @IBOutlet weak var feedRelatedVideosLoadingRetryButton: UIButton!
    @IBOutlet weak var feedRelatedVideosLoadingActivityIndicator: UIActivityIndicatorView!
    
    
    // MARK: - Public properties -
  
    var presenter: FeedDetailPresenterInterface!

    // MARK: - Lifecycle -

    override func viewDidLoad() {
        super.viewDidLoad()
        initialSetup()
    }
    
    override func viewDidAppear(_ animated: Bool) {
        super.viewDidAppear(animated)
        presenter.viewDidAppear(animated: animated)
    }
    
    
}

// MARK: - Functions -

extension FeedDetailViewController {
    
    private func initialSetup() {
        
    }
    
}

// MARK: - Extensions -

extension FeedDetailViewController: FeedDetailViewInterface {
    

}



