//
//  FeedDetailInterfaces.swift
//  TheVargo
//
//  Created by Andre Souza on 09/07/2018.
//  Copyright (c) 2018 AndreSamples. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum FeedDetailNavigationOption {
}

protocol FeedDetailWireframeInterface: WireframeInterface {
    func navigate(to option: FeedDetailNavigationOption)
}

protocol FeedDetailViewInterface: ViewInterface {
    func showPlaceInfo(_ item: PlaceDetailInterface)
    func showError(error: ErrorInterface, target: Any?, action: Selector?)
    func showLoading(_ loading: Bool)
}

protocol FeedDetailPresenterInterface: PresenterInterface {
    func setPlaceDetailFromSplitViewController(_ placeId: String)
    
}

protocol FeedDetailInteractorInterface: InteractorInterface {
     func get(placeId: String, completion: @escaping (RequestResultType<Place>) -> Void) 
}

protocol PlaceDetailInterface: PlaceItemInterface {
    var location: Location? { get }
    var address: String? { get }
    var phone: String? { get }
}
