//
//  FeedListInterfaces.swift
//  TheVargo
//
//  Created by Andre Souza on 09/07/2018.
//  Copyright (c) 2018 AndreSamples. All rights reserved.
//
//  This file was generated by the 🐍 VIPER generator
//

import UIKit

enum FeedListNavigationOption {
    case detail(FeedContent)
}

protocol FeedListWireframeInterface: WireframeInterface {
    func navigate(to option: FeedListNavigationOption)
}

protocol FeedListViewInterface: ViewInterface {
    func reloadData()
    func showError(error: ErrorInterface, target: Any?, action: Selector?)
    func showFooterLoading(_ loading: Bool)
    func showLoading(_ loading: Bool)
    func showFooterUpdatedMessage(message: String)
}

extension FeedListViewInterface {
    func showError(error: ErrorInterface, target: Any? = nil, action:Selector? = nil) {
        return showError(error: error, target: target, action: action)
    }
}

protocol FeedListPresenterInterface: PresenterInterface {
    func _loadMoreItems()
    func numberOfSections() -> Int
    func numberOrItems(in section: Int) -> Int
    func item(at indexPath: IndexPath) -> FeedListItemInterface?
    func didSelectItem(at indexPath: IndexPath)
}

protocol FeedListInteractorInterface: InteractorInterface {
    func getFeeds(page: Int, completion: @escaping (RequestResultType<Feed>) -> Void)
}

protocol FeedListItemInterface {
    var title: String? { get }
    var description: String? { get }
    var imageURL: String? { get }
    var isVideo: Bool { get }
}
